### ISSUE TITLE
Two undeclared variables

### ISSUE THREAD

**Issue by ninadsutrave** [zokioki/places-autocomplete#1]
What are the variables mapboxglMap and mapboxgl.accessToken in the autocomplete setting up?

const autocomplete = new PlacesAutocomplete({
  mapboxToken: mapboxgl.accessToken,
  mapInstance: mapboxglMap,
  debounce: 300
});

**Comment by zokioki** [comment]
Hey Ninad, `mapboxgl` is the imported object from the `mapbox-gl` library and the `mapboxglMap` is meant to be an instance of `mapboxgl.Map` in that example - just [updated](https://github.com/zokioki/places-autocomplete/commit/fd97899c5a94b7189e2f994b29a419c2b53cd0b2) the snippet in the README to make those clearer.

**Comment by ninadsutrave** [comment]
Thanks your for response. 
While that did solve the issue, I also wish details about mapbox options had also been mentioned (would've same my time tbh). Anyway, I've created a pull request by adding some details that I'm sure would help our fellow developers. Have a look and if all okay you could merge them.

**Comment by zokioki** [comment]
Thanks for submitting a PR. I feel that the instructions don't need to go too into depth on the `mapbox-gl` library since the autocomplete can technically be used independent of the map as well. I have [updated](https://github.com/zokioki/places-autocomplete/commit/6012efbcf61a2f0b25936ad899ec04ed7a132393) the instructions with the minimum required config to render a map and have included some links for the `mapbox-gl` documentation. 

Hope those changes are helpful.

**Comment by ninadsutrave** [comment]
Np. Thank you!
